# Generated by Django 4.0.1 on 2022-01-24 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='state',
            new_name='state_id',
        ),
    ]
