# Generated by Django 4.0.1 on 2022-01-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_rename_state_session_state_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='state_id',
            new_name='state',
        ),
        migrations.AddField(
            model_name='session',
            name='token',
            field=models.CharField(default='no token', max_length=200),
            preserve_default=False,
        ),
    ]
