# Generated by Django 4.0.1 on 2022-01-26 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0003_rename_state_id_session_state_session_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['id']},
        ),
    ]
