# Generated by Django 4.0.1 on 2022-01-27 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0007_alter_session_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='token',
            field=models.JSONField(null=True),
        ),
    ]
